# Generated by Django 4.2.2 on 2023-06-28 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSessionToken",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("token", models.TextField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="app.user_info",
                    ),
                ),
            ],
            options={
                "db_table": "user_session",
            },
        ),
    ]
