# Generated by Django 4.2.2 on 2023-06-29 04:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_usersessiontoken"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post_info",
            name="name",
        ),
    ]
