# Generated by Django 4.2.2 on 2023-06-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_post_info_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="liked_saved",
            name="is_liked",
            field=models.BooleanField(default=False),
        ),
    ]
